### PR TITLE
Layout files for Swift Pacakge Manager

### PR DESCRIPTION
**Pull request by BlakeLucchesi**
- Initial work to layout the files/folders in the manner that SPM expects them to be.
- Uses the conditional macros to use Glibc or Darwin depending on the platform.

### CODE REVIEW

**Comment by BlakeLucchesi** [comment]
I followed the comments from this guy's blog post so that we don't break carthage/pods support by re-arranging all the files, however, I don't know if this is required by another package, if SPM is smart enough to go into the SwiftPackageManager folder to actually build it.  Alas, I figured I would commit this up anyways as it's a helpful start at attempting to build the package on linux.

**Comment by BlakeLucchesi** [comment]
It looks like support for excluding paths from the swift build process was implemented on 2015-12-11, once thats in the next distro it would be possible to move the Sources folder back up to the top level, and then just add the ARI folders into the list of excludes so SPM doesn't try and build through them.

@see https://github.com/apple/swift-package-manager/pull/57

**Comment by helje5** [comment]
This goes against master, lets keep this stuff in the linux feature branch for now as Swift 2.2 is incompatible with 2.1.

**Comment by helje5** [comment]
Also, lets wait for the 2015-12-11 version then.

**Comment by euskadi31** [comment]
:+1:

**Comment by helje5** [comment]
Any news on this?

**Comment by helje5** [comment]
Source is now layout for SPM.

**Pull request closed without merging**
