### PR TITLE
Rename product and scheme to SwiftSockets

### PR DESCRIPTION
**Pull request by izqui**
Now that we have the Pod ready, the problem is that CocoaPods names the framework in the same way as the pod (completely ignoring the xCode project), so right now if you build directly with xCode or with Carthage, the framework is named `ARISockets.framework`, but if you fetch the dependency with CocoaPods it is named `SwiftSockets.framework`.

What I did in this PR is renaming everything needed in order for the framework to be always built as `SwiftSockets.framework` (which IMHO is a way cooler name :+1:)

I think what Carthage fetches by default is the last tagged release, so you would need to do that after merging.

### CODE REVIEW

**Comment by helje5** [comment]
Hm, if we do this I'd rather rename the whole thing. Might give it a shot later today.

**Comment by helje5** [comment]
Please give the rename-to-SwiftSockets branch a try. Does it still need a scheme or something? If it's OK, I'll merge it in and make a release later.

**Comment by izqui** [comment]
Looking good, I also changed the name of the scheme in #14, it is not needed but otherwise when building with Carthage it says "Building sheme ARISockets"

**Comment by helje5** [comment]
Is this still open or are we good here? If not, what do you want me to change?

**Comment by izqui** [comment]
I think we are good! Thanks

2015-12-10 10:48 GMT+01:00 Helge Heß <notifications@github.com>:

**Pull request closed without merging**
